project:
  type: book

book:
  title: "LV: Analysing Quality of Care data - resources"
  author: 
    - name: "Catherine Blatter"
  date: today
  chapters:
    - index.qmd
    - dupes.qmd
    - missings.qmd
    - dataviz.qmd

bibliography: references.bib

echo: true

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    from: markdown+emoji
  pdf:
    documentclass: scrreprt

execute: 
  freeze: auto

